### ISSUE TITLE
Improve sorting

### ISSUE THREAD

**Issue by wyuenho** [wyuenho/backgrid#282]
Sorting is problematic for a number of reasons:
- [x] No obvious way to set default sorting (#256, #222)
- [x] No obvious way to sort programmatically
- [ ] Can't sort by multiple columns (#143)
- [x] Can't sort if the header is disabled (#233)
- [x] HeaderCell is doing too many things too inefficiently.

I really need a long day to fix these issues once and for all. :tired_face:
